export { createEditTable } from './create';
export {
    setTableData,
    getCurrentStatus,
    getAllRows,
    setStatus,
    addRow,
    delRow,
    getChangedRows,
    edit,
    cancelEdit,
    save,
    pasteRow,
    setValByKey,
    getColValue,
    addRowValue,
    setColValue,
    setEditableByKey,
    hideEditTableColByKey,
    showEditTableColByKey,
    setValByKeyAndRowNumber,
    getAllRowsRemoveKeys,
    getNumberOfRows,
    setColValueByData,
    getAllData,
    getEditTableCacheDataById,
    filterEmptyRows,
    getTableCheckedRows,
    selectAllTableRows,
    reverseTableSelected,
    deleteRowsByRowId,
    deleteRowsByIndex,
} from './methods';

